"""LUD-25 `ct1` taproot note locks: lock a note to ct1<Q>, redeem it with a
`cw1` script-path spend verified by Bitcoin Core's interpreter (lnurlcashkernel).

The vectors are generated by lnurl-wallet (src/addons/taproot/ct1Interop.test.ts),
i.e. by an independent implementation of BIP-341/342 signing."""

import json
import pathlib
import types
from hashlib import sha256
from os import urandom

import pytest
from fastapi.testclient import TestClient

from lnurl_mint import bech32m, ct1
from lnurl_mint.db import notes
from tests.conftest import FakeNode

pytest.importorskip("lnurlcashkernel")

VECTORS = json.loads((pathlib.Path(__file__).parent / "vectors" / "wallet_ct1_vectors.json").read_text())["vectors"]
BY_NAME = {v["name"]: v for v in VECTORS}


@pytest.fixture(autouse=True)
def _reset_ct1_notes():
    for vector in VECTORS:
        notes.conn.execute("DELETE FROM notes WHERE id = ?", (vector["output_key"],))
        notes.conn.execute("DELETE FROM burns WHERE burn_key = ?", (vector["output_key"],))
    notes.conn.commit()
    yield


def _at(monkeypatch: pytest.MonkeyPatch, now: int) -> None:
    monkeypatch.setattr(ct1, "time", types.SimpleNamespace(time=lambda: float(now)))


def _lock(client: TestClient, mint_note, vector: dict, ct1_ref: str | None = None) -> None:
    """Rotate a fresh legacy note into `ct1<Q>` (the wallet's note.lockToPubkey)."""
    k1 = mint_note(vector["amount_msat"])
    response = client.get(f"/w/cb?k1={k1}&p1={ct1_ref or vector['ct1']}")
    assert not _refused(response) and response.json().get("sig"), response.text
    notes.conn.execute("UPDATE notes SET locked_at = ? WHERE id = ?", (vector["locked_at"], vector["output_key"]))
    notes.conn.commit()


def _refused(response) -> bool:
    return response.json().get("status") == "ERROR"


def _redeem(client: TestClient, cw1: str, p1: str | None = None):
    return client.get(f"/w/cb?k1={cw1}&p1={p1 or sha256(urandom(32)).hexdigest()}")


@pytest.mark.parametrize("vector", VECTORS, ids=[v["name"] for v in VECTORS])
def test_derive_output_key_matches_wallet(vector):
    assert ct1.derive_output_key(
        bytes.fromhex(vector["leaf_script"]), bytes.fromhex(vector["control_block"])
    ).hex() == (vector["output_key"])


def test_derive_output_key_rejects_malformed_control_block():
    assert ct1.derive_output_key(b"\x51", b"\xc0" + b"\x00" * 31) is None
    assert ct1.derive_output_key(b"\x51", b"\xc0" + b"\x00" * 40) is None


@pytest.mark.parametrize("vector", VECTORS, ids=[v["name"] for v in VECTORS])
def test_lock_then_redeem_by_script_path(client, node: FakeNode, mint_note, monkeypatch, vector):
    _lock(client, mint_note, vector)
    _at(monkeypatch, vector["now"])
    p1 = sha256(urandom(32)).hexdigest()

    response = _redeem(client, vector["cw1"], p1)
    assert not _refused(response), response.text
    assert len(bytes.fromhex(response.json()["sig"])) == 65  # p1 is a legacy hash: raw-hex certificate
    assert notes.note_amount(vector["output_key"]) is None  # burned
    assert notes.note_amount(p1) == vector["amount_msat"]  # re-issued under p1

    # LUD-25 "Retrying a mutation": the same request again replays its result
    assert _redeem(client, vector["cw1"], p1).json() == response.json()
    # ...but a different p1 is a genuine double-spend
    assert _refused(_redeem(client, vector["cw1"]))


def test_informational_get_accepts_cw1_and_certifies(client, node, mint_note, monkeypatch):
    vector = BY_NAME["pk"]
    _lock(client, mint_note, vector)
    _at(monkeypatch, vector["now"])
    data = client.get(f"/w?k1={vector['cw1']}").json()
    assert data["minWithdrawable"] == data["maxWithdrawable"] == vector["amount_msat"]
    amount, _ = bech32m.decode_cs1(data["sig"])
    assert amount == vector["amount_msat"]
    assert notes.note_amount(vector["output_key"]) == vector["amount_msat"]  # informational: not burned


def test_cltv_leaf_refused_before_locktime_and_burns_nothing(client, node, mint_note, monkeypatch):
    vector = BY_NAME["cltv"]
    _lock(client, mint_note, vector)
    _at(monkeypatch, vector["locktime"] - 1)
    assert _refused(_redeem(client, vector["cw1"]))
    assert notes.note_amount(vector["output_key"]) == vector["amount_msat"]


def test_cltv_rejection_names_the_specific_reason_not_a_generic_one(client, node, mint_note, monkeypatch):
    """A cw1 that legitimately names a real, still-locked note, but whose
    own script conditions the mint's clock hasn't cleared yet, must say so
    specifically - never collapse into the same "invalid or already spent"
    wording a wrong or already-burned secret gets (see router.py's own
    _cw1_rejection_reason): those are genuinely different situations, and a
    cw1 discloses its whole secret already, so there's nothing unsafe about
    being specific here."""
    vector = BY_NAME["cltv"]
    _lock(client, mint_note, vector)
    _at(monkeypatch, vector["locktime"] - 1)

    response = _redeem(client, vector["cw1"])
    assert _refused(response)
    reason = response.json()["reason"]
    assert "future" in reason
    assert "already spent" not in reason.lower()
    assert notes.note_amount(vector["output_key"]) == vector["amount_msat"]  # never burned


def test_informational_get_also_names_the_specific_cw1_rejection_reason(client, node, mint_note, monkeypatch):
    vector = BY_NAME["cltv"]
    _lock(client, mint_note, vector)
    _at(monkeypatch, vector["locktime"] - 1)

    response = client.get(f"/w?k1={vector['cw1']}")
    assert _refused(response)
    reason = response.json()["reason"]
    assert "future" in reason
    assert reason != "Unknown note."


def test_cw1_matching_no_locked_note_stays_ambiguous(client, node, monkeypatch):
    """Unlike a genuinely actionable rejection, a cw1 whose derived output
    key simply isn't locked to any note here must stay in the same
    ambiguous bucket a wrong or already-burned legacy k1 does - it may
    never have existed, or may already be spent, and the mint can't (and
    shouldn't try to) tell those apart."""
    vector = BY_NAME["pk"]
    _at(monkeypatch, vector["now"])
    response = _redeem(client, vector["cw1"])
    assert _refused(response)
    assert response.json()["reason"] == "Invalid or already spent k1."


def test_cw1_shaped_value_without_the_kernel_says_so_specifically(client, node, monkeypatch):
    monkeypatch.setattr(ct1, "kernel", None)
    response = _redeem(client, "cw1" + "q" * 20)
    assert _refused(response)
    assert "does not support ct1" in response.json()["reason"]


def test_csv_leaf_refused_before_maturity(client, node, mint_note, monkeypatch):
    vector = BY_NAME["csv"]
    _lock(client, mint_note, vector)
    _at(monkeypatch, vector["locked_at"] + 2047)  # one second short of 4 * 512
    assert _refused(_redeem(client, vector["cw1"]))
    assert notes.note_amount(vector["output_key"]) == vector["amount_msat"]


def test_cw1_never_opens_a_cp1_note(client, node, mint_note, monkeypatch):
    """A note registered as cp1<Q> has no script path even if Q happens to be a
    taproot output key - only the ct1 flag opts a note into cw1 redemption."""
    vector = BY_NAME["pk"]
    cp1 = bech32m.encode_cp1(bytes.fromhex(vector["output_key"]))
    _lock(client, mint_note, vector, ct1_ref=cp1)
    _at(monkeypatch, vector["now"])
    assert _refused(_redeem(client, vector["cw1"]))
    assert notes.note_amount(vector["output_key"]) == vector["amount_msat"]


def test_tampered_witness_is_refused(client, node, mint_note, monkeypatch):
    vector = BY_NAME["pk"]
    _lock(client, mint_note, vector)
    _at(monkeypatch, vector["now"])
    spend = ct1.kernel.decode_cw1(vector["cw1"])
    sig = bytearray(spend.witness[0])
    sig[5] ^= 1
    forged = _encode_cw1(spend, [bytes(sig)])
    assert _refused(_redeem(client, forged))
    assert notes.note_amount(vector["output_key"]) == vector["amount_msat"]


def test_wrong_leaf_for_note_is_refused(client, node, mint_note, monkeypatch):
    """A cw1 for a DIFFERENT taproot output cannot open this note."""
    locked, other = BY_NAME["pk"], BY_NAME["hashlock"]
    _lock(client, mint_note, locked)
    _at(monkeypatch, other["now"])
    assert _refused(_redeem(client, other["cw1"]))
    assert notes.note_amount(locked["output_key"]) == locked["amount_msat"]


def test_mint_straight_to_ct1_then_redeem(client, node: FakeNode, monkeypatch):
    vector = BY_NAME["pk"]
    response = client.get(f"/p/cb?amount={vector['amount_msat']}&comment={vector['ct1']}")
    assert response.json().get("pr"), response.text
    node.settled.add(sha256(node.last_preimage).hexdigest())
    _at(monkeypatch, vector["now"])
    response = _redeem(client, vector["cw1"])
    assert not _refused(response), response.text


def test_ct1_refused_without_the_kernel(client, node, mint_note, monkeypatch):
    monkeypatch.setattr(ct1, "kernel", None)
    vector = BY_NAME["pk"]
    k1 = mint_note(vector["amount_msat"])
    response = client.get(f"/w/cb?k1={k1}&p1={vector['ct1']}")
    assert _refused(response)
    assert client.get(f"/w?k1={k1}").json()["maxWithdrawable"] == vector["amount_msat"]  # nothing burned


def _encode_cw1(spend, witness: list[bytes]) -> str:
    payload = spend.locktime.to_bytes(4, "big") + spend.sequence.to_bytes(4, "big")
    for part in (spend.script, spend.control_block, *witness):
        payload += len(part).to_bytes(2, "big") + part
    return bech32m.encode("cw", payload)
